## Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
## More GitHub Actions for Azure: https://github.com/Azure/actions
## More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions
#
#name: Build and deploy Python project to Azure Function App - azure-function-omartushevskyi
#
#on:
#  push:
#    branches:
#      - main
#  workflow_dispatch:
#
#env:
#  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
#  PYTHON_VERSION: '3.9' # set this to the python version to use (supports 3.6, 3.7, 3.8)
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name: Setup Python version
#        uses: actions/setup-python@v1
#        with:
#          python-version: ${{ env.PYTHON_VERSION }}
#
#      - name: Create and start virtual environment
#        run: |
#          python -m venv venv
#          source venv/bin/activate
#
#      - name: Install dependencies
#        run: pip install -r requirements.txt
#
#      # Optional: Add step to run tests here
#
#      - name: Upload artifact for deployment job
#        uses: actions/upload-artifact@v2
#        with:
#          name: python-app
#          path: |
#            .
#            !venv/
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    environment:
#      name: 'Production'
#      url: ${{ steps.deploy-to-function.outputs.webapp-url }}
#
#    steps:
#      - name: Download artifact from build job
#        uses: actions/download-artifact@v2
#        with:
#          name: python-app
#          path: .
#      - name: Login via Az module
#        uses: azure/login@v1
#        with:
#          creds: ${{secrets.AZURE_CREDENTIALS}}
#          enable-AzPSSession: true
#      - name: 'Deploy to Azure Functions'
#        uses: Azure/functions-action@v1
#        id: fa
#        with:
#          app-name: 'azure-function-omartushevskyi'
#          slot-name: 'Production'
#          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
#          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F6B0617F7FB3424F926264870A9FEF9B }}
#          scm-do-build-during-deployment: true
#          enable-oryx-build: true

name: Deploy Python project to Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:

# CONFIGURATION
# For help, go to https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_FUNCTIONAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  AZURE_FUNCTIONAPP_NAME: omart795047176 # set this to your application's name
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'   # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.7'                 # set this to the python version to use (supports 3.6, 3.7, 3.8)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v1
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: 'Resolve Project Dependencies Using Pip'
      shell: bash
      run: |
        pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        python -m pip install --upgrade pip
        pip install -r requirements.txt --target=".python_packages/lib/site-packages"
        popd
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
